CREATE TABLE IF NOT EXISTS automation_module (
    id BIGINT PRIMARY KEY,
    code VARCHAR(64) NOT NULL UNIQUE,
    name VARCHAR(128) NOT NULL,
    description VARCHAR(512) NOT NULL,
    owner VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    deleted TINYINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_embedding_config (
    id BIGINT PRIMARY KEY,
    enabled TINYINT NOT NULL DEFAULT 1,
    provider VARCHAR(64) NOT NULL,
    api_url VARCHAR(512) NOT NULL,
    api_key VARCHAR(1024),
    model VARCHAR(128) NOT NULL,
    dimension INT NOT NULL,
    milvus_url VARCHAR(512) NOT NULL,
    collection_name VARCHAR(128) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
